version: "'3.8'"
services:
    db:
        image: feathr_postgres
        container_name: feathr_postgres
        build:
            context: .
            dockerfile: Dockerfile-postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=metastore_db
        ports:
            - '${HOST_POSTGRES_PORT}:5432'
        volumes:
            - ${HOST_POSTGRES_DATA_DIR}/data:/var/lib/postgresql/data
            - $PWD/registry/sql-scripts:/docker-entrypoint-initdb.d

    ui_feathr_app:
        build:
            context: .
            dockerfile: FeathrSandbox.Dockerfile
        depends_on:
             - db
        container_name: ui-feathr-container
        image: feathrfeaturestore/feathr-sandbox-full:latest
        environment:
            - FEATHRUI_SQLALCHEMYSTORE_MAX_OVERFLOW=0
            - FEATHRUI_SQLALCHEMYSTORE_POOL_SIZE=30
            - FEATHR_SANDBOX_REGISTRY_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB_NAME}
            - GRANT_SUDO=no # yes for debug
            - REGISTRY_DEBUGGING=True # True for debug
        # network_mode: "host"
        # volumes: # uncomment for debug
        #     - ./registry/sql-registry:/usr/src/registry/sql-registry
        ports:
            - 8081:80
        #command: ["sh", "-c", "sleep 20 && PYTHONIOENCODING='UTF-8' && /bin/bash -c 'ls /usr/src/registry' && /bin/bash -c 'while true; do sleep 2; done'"]
        command: ["sh", "-c", "sleep 20 && PYTHONIOENCODING='UTF-8' && /bin/bash -c '/usr/src/registry/start_local.sh'"]


