
api_version: 1
project_config:
  project_name: product_recommendation

spark_config:
  # choice for spark runtime. Currently support: azure_synapse, databricks, local
  spark_cluster: 'local'
  spark_result_output_parts: '1'
  local:
    master: 'local[*]'
    spark.sql.shuffle.partitions: '12'
    feathr_runtime_location: "./vnpt_feathr-0.0.1.jar"

online_store:
  mongodb:
    # mongodb configs
    host: '127.0.0.1'
    port: 27017
    database: _feathr
    
  redis:
    # Redis configs to access Redis cluster
    host: '172.20.0.4'
    port: 6379
    ssl_enabled: False
    cluster_mode: True


feature_registry:
  # The API endpoint of the registry service
  api_endpoint: "http://127.0.0.1:8081/api/v1"
